const candidates = [
  {
    id: 1,
    fullName: 'John Doe',
    category: 'Engineering',
    type: 'Full-Time',
    location: 'San Francisco, CA',
    date: '2024-07-01',
    isInvitedToInterview: true,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    category: 'Design',
    type: 'Part-Time',
    location: 'New York, NY',
    date: '2024-07-02',
    isInvitedToInterview: false,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",
  },
  {
    id: 3,
    fullName: 'Samuel Green',
    category: 'Marketing',
    type: 'Contract',
    location: 'Austin, TX',
    date: '2024-07-03',
    isInvitedToInterview: false,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",

  },
  {
    id: 4,
    fullName: 'Emily Brown',
    category: 'Product Management',
    type: 'Internship',
    location: 'Seattle, WA',
    date: '2024-07-04',
    isInvitedToInterview: true,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",
  },
  {
    id: 5,
    fullName: 'Michael Johnson',
    category: 'Engineering',
    type: 'Full-Time',
    location: 'Denver, CO',
    date: '2024-07-05',
    isInvitedToInterview: false,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",

  },
  {
    id: 6,
    fullName: 'Laura Wilson',
    category: 'HR',
    type: 'Contract',
    location: 'Chicago, IL',
    date: '2024-07-06',
    isInvitedToInterview: false,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",

  },
  {
    id: 7,
    fullName: 'William Adams',
    category: 'Sales',
    type: 'Part-Time',
    location: 'Miami, FL',
    date: '2024-07-07',
    isInvitedToInterview: true,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",

   
  },
  {
    id: 8,
    fullName: 'Sophia Martinez',
    category: 'Finance',
    type: 'Full-Time',
    location: 'Los Angeles, CA',
    date: '2024-07-08',
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",

    isInvitedToInterview: false,
  },
  {
    id: 9,
    fullName: 'David Lopez',
    category: 'IT Support',
    type: 'Full-Time',
    location: 'Phoenix, AZ',
    date: '2024-07-09',
    isInvitedToInterview: false,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",
  },
  {
    id: 10,
    fullName: 'Olivia Taylor',
    category: 'Engineering',
    type: 'Internship',
    location: 'Boston, MA',
    date: '2024-07-10',
    isInvitedToInterview: true,
    image: 'https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png',
    experience:"Junior",
  },
];

export default candidates;
