export const jobs = [
  {
    id: 1,
    title: "Software Depressor",
    company: "gmel29206",
    category: "Customer",
    type: "Full Time",
    date: "November 28, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 2,
    title: "Marketing Support Student 1",
    company: "TaskBee",
    category: "Automotive Jobs",
    type: "One-Time",
    date: "November 27, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 3,
    title: "Marketing Support Student",
    company: "sugirrakevin99",
    category: "",
    type: "",
    date: "November 20, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 4,
    title: "Junior Graphic Designer (Web)",
    company: "Employer",
    category: "Design, Development",
    type: "Full Time",
    date: "June 20, 2021",
    location: "New York",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 5,
    title: "Finance Manager & Health",
    company: "Medium",
    category: "Design",
    type: "Full Time",
    date: "May 3, 2021",
    location: "New York",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 6,
    title: "Software Depressor",
    company: "gmel29206",
    category: "Customer",
    type: "Full Time",
    date: "November 28, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 7,
    title: "Marketing Support Student 1",
    company: "TaskBee",
    category: "Automotive Jobs",
    type: "One-Time",
    date: "November 27, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },

  {
    id: 8,
    title: "Marketing Support Student",
    company: "sugirrakevin99",
    category: "",
    type: "",
    date: "November 20, 2024",
    location: "",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    isApplied:true,
  },
  {
    id: 9,
    title: "Junior Graphic Designer (Web)",
    company: "Employer",
    category: "Design, Development",
    type: "Full Time",
    date: "June 20, 2021",
    location: "New York",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
  },
  {
    id: 10,
    title: "Finance Manager & Health",
    company: "Medium",
    category: "Design",
    type: "Full Time",
    date: "May 3, 2021",
    location: "New York",
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
  },
];

export const companiesData = [
  {
    id: 1,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "Software Engineer",
    name: "TechCorp",
    category: "Technology",
    location: "San Francisco, CA",
    date: "22-11-2024",
  },
  {
    id: 2,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "Product Manager",
    name: "InnovateX",
    category: "E-commerce",
    location: "New York, NY",
    date: "22-11-2024",
  },
  {
    id: 3,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "UI/UX Designer",
    name: "DesignHub",
    category: "Design",
    location: "Los Angeles, CA",
    date: "22-11-2024",
  },
  {
    id: 4,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "Marketing Specialist",
    name: "Brandify",
    category: "Marketing",
    location: "Chicago, IL",
    date: "22-11-2024",
  },
  {
    id: 5,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "Data Analyst",
    name: "DataScope",
    category: "Data Science",
    location: "Seattle, WA",
    date: "22-11-2024",
  },
  {
    id: 6,
    logo: "https://www.job.taskbees.net/wp-content/uploads/wp-job-board-pro-uploads/_employer_featured_image/2024/11/TaskBee-4-150x150.png",
    title: "Full Stack Developer",
    name: "CodeSolutions",
    category: "Software Development",
    location: "Austin, TX",
    date: "22-11-2024",
  },
];

export default companiesData;
